# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  workflow_dispatch:
  push:
    branches: [main, master]
    tags: ['*']

name: pkgdown-gh-pages

jobs:
  pkgdown-gh-pages:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2

      - uses: r-lib/actions/setup-pandoc@v2-branch

      - uses: r-lib/actions/setup-r@v2-branch
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2-branch
        with:
          extra-packages:
            any::pkgdown
            any::ggplot2
            any::tmap
            paleolimbot/ggspatial
          needs: website

      - name: Build site
        run: Rscript -e 'pkgdown::build_site_github_pages(new_process = FALSE, install = FALSE)'

      - name: Deploy to GitHub pages ðŸš€
        if: github.event_name != 'pull_request'
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          clean: false
          branch: gh-pages
          folder: docs
